apiVersion: v1
kind: Pod
metadata:
    name: my-pod1
    labels:
      app: frontend-modified
spec:
    containers:
        - name: myapp
          image: gcr.io/tatvic-gcp-dev-team/jaygiri12345/cl1@sha256:87fff477611a9afb35c2107607c520e2c2ea9f8183600b38949ed39a05e851ee
          env:
          - name: BCK_URL
            valueFrom:
              secretKeyRef:
                name: secret-frontend
                key: bck_url
          